name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.80.0
        TARGET_REPO: diogoalexsmachado/nstargg-website
        TARGET_BRANCH: gh-pages
        TOKEN: ${{ secrets.GH_TOKEN }}
        CNAME: stg.nstargg.com